version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: always
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: myuser
      KC_DB_PASSWORD: mypassword
      KC_DB_DATABASE: mydb
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  backend:
    build:
      context: ./expressjsdemo
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASS: mypassword
      DB_NAME: mydb
      DB_DIALECT: postgres
      KEYCLOAK_URL: http://keycloak:8080
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - keycloak

  frontend:
    build:
      context: ./products-app
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
